-- Squashed baseline (replaces 0001..0036).
--
-- This file is generated by `cargo run -p execlaw-core --bin
-- dump_baseline_schema` against a fresh DB after applying
-- the historical migration chain. Do NOT edit it by hand —
-- changes to the live schema land in NEW migration files
-- (0002, 0003, …) just like before. The baseline is
-- immutable once shipped.
--
-- Operators upgrading from a pre-baseline install: this
-- repo is pre-v1 and the operator has explicitly accepted
-- a one-time `rm execlaw.db` to land on the baseline
-- cleanly. Any future schema change uses a normal
-- additive migration on top of this file.

-- =========================================================================
-- TABLES
-- =========================================================================

CREATE TABLE config_alert_routing (
    key    TEXT PRIMARY KEY,
    value  TEXT NOT NULL
);

CREATE TABLE config_audit (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts          INTEGER NOT NULL,
    actor       TEXT    NOT NULL,
    table_name  TEXT    NOT NULL,
    row_id      TEXT    NOT NULL,
    old_json    BLOB,
    new_json    BLOB
);

CREATE TABLE config_backends (
    purpose             TEXT    PRIMARY KEY,    -- Standard | Reasoning | Guardrail | VoiceSTT | VoiceTTS
    inference_backend   TEXT    NOT NULL,       -- PluginId, e.g. "service-vllm"
    model_spec_json     BLOB    NOT NULL,
    gpu_id              TEXT,
    endpoint            TEXT,
    notes               TEXT,
    created_at          INTEGER NOT NULL,
    updated_at          INTEGER NOT NULL
, reasoning_enabled INTEGER NOT NULL DEFAULT 0, mode TEXT NOT NULL DEFAULT 'external');

CREATE TABLE config_general (
    -- Singleton row guard. The CHECK forces every INSERT to use 1 so
    -- the table can never grow beyond a single row.
    id              INTEGER NOT NULL PRIMARY KEY CHECK (id = 1),
    start_on_boot   INTEGER NOT NULL DEFAULT 1 CHECK (start_on_boot IN (0, 1)),
    bind_address    TEXT    NOT NULL DEFAULT '127.0.0.1:3030',
    updated_at      INTEGER NOT NULL
, setup_wizard_dismissed_at INTEGER, hf_secondary_caches_json TEXT, history_retention_days INTEGER NOT NULL DEFAULT 30);

CREATE TABLE config_hardware_profile_overrides (
    gpu_id         TEXT    PRIMARY KEY,
    override_json  BLOB    NOT NULL,
    set_by         TEXT    NOT NULL,
    set_at         INTEGER NOT NULL,
    reason         TEXT
);

CREATE TABLE config_mcp_servers (
    id                       TEXT    PRIMARY KEY,                -- slug
    display_name             TEXT    NOT NULL,
    transport                TEXT    NOT NULL,                   -- "stdio" | "streamable_http"
    -- stdio-specific:
    command                  TEXT,
    args_json                TEXT,                               -- JSON array
    env_json                 TEXT,                               -- JSON map (kept opaque)
    cwd                      TEXT,
    -- http-specific (Phase 8c follow-up):
    url                      TEXT,
    auth_secret_ref          TEXT,
    -- common:
    enabled                  INTEGER NOT NULL DEFAULT 1,
    default_allowed_classes  TEXT    NOT NULL DEFAULT '["Controller"]', -- JSON array
    status                   TEXT,                               -- "connected" | "disconnected" | "error"
    last_error               TEXT,
    created_at               INTEGER NOT NULL,
    updated_at               INTEGER NOT NULL
);

CREATE TABLE config_personality (
    scope_kind          TEXT    NOT NULL,
    scope_ref           TEXT    NOT NULL,
    display_name        TEXT    NOT NULL DEFAULT '',
    role                TEXT    NOT NULL DEFAULT '',
    tone                TEXT    NOT NULL DEFAULT '',
    communication_style TEXT    NOT NULL DEFAULT '',
    initiative          TEXT    NOT NULL DEFAULT '',
    about_agent         TEXT    NOT NULL DEFAULT '',
    about_controller    TEXT    NOT NULL DEFAULT '',
    custom_instructions TEXT    NOT NULL DEFAULT '',
    voice_id            TEXT,
    -- For overrides: a JSON array of field names that the operator
    -- explicitly set on this scope. The composer treats fields NOT in
    -- this list as "not in override" (use base) instead of "blank in
    -- override" (force blank). Default-scope rows ignore this column —
    -- every field is implicitly present at the default level.
    override_fields_json TEXT NOT NULL DEFAULT '[]',
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          INTEGER NOT NULL,
    updated_at          INTEGER NOT NULL,
    PRIMARY KEY (scope_kind, scope_ref),
    CHECK (scope_kind IN ('default', 'conversation')),
    CHECK (scope_kind <> 'default' OR scope_ref = '')
);

CREATE TABLE config_research (
    -- Singleton constraint: only id=1 is ever inserted; the row
    -- itself is seeded just below so `GET /api/admin/settings/research`
    -- on a fresh DB doesn't 500.
    id                          INTEGER PRIMARY KEY CHECK (id = 1),
    -- Hard kill-switch: a runner past this wall-clock cap is
    -- terminated regardless of phase. Default 30 min.
    max_wall_clock_minutes      INTEGER NOT NULL DEFAULT 30,
    -- Total subagent token ceiling — sum across plan + gather +
    -- synthesize. Default 100000 tokens.
    max_total_tokens            INTEGER NOT NULL DEFAULT 100000,
    -- Planner cap on sub-query count. Default 12.
    max_subqueries              INTEGER NOT NULL DEFAULT 12,
    -- Gather-phase parallelism. Default 3 (Semaphore size in C4).
    parallel_workers            INTEGER NOT NULL DEFAULT 3,
    -- Per-sub-query URL fetch cap. Default 5.
    max_urls_per_subquery       INTEGER NOT NULL DEFAULT 5,
    -- Belt-and-braces total page cap (kills further fetches once
    -- exceeded, even if individual sub-queries haven't maxed out).
    -- Default 60.
    max_pages_total             INTEGER NOT NULL DEFAULT 60,
    -- Idle-runner kill: if no progress event in this many seconds,
    -- the supervisor terminates and marks failed. Default 120s.
    auto_cancel_after_idle_secs INTEGER NOT NULL DEFAULT 120,
    -- Phase-gate vocabulary:
    --   none         — runner advances straight through plan→
    --                  gather→synthesize, no operator confirms
    --   plan_only    — pause after plan, await operator confirm
    --   every_phase  — pause between every phase (C6)
    -- Default `plan_only`: gives the operator a one-click confirm
    -- before the expensive gather phase fires.
    phase_gates                 TEXT    NOT NULL DEFAULT 'plan_only',
    -- Search provider id ("duckduckgo", "brave", …). NULL means
    -- "inherit from Settings → Search" (forthcoming).
    default_search_provider     TEXT,
    updated_at                  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE config_research_quota (
    key    TEXT PRIMARY KEY,
    value  TEXT NOT NULL
);

CREATE TABLE config_routines (
    id                       TEXT    PRIMARY KEY,
    name                     TEXT    NOT NULL,
    schedule_cron            TEXT    NOT NULL,    -- 5-field cron
    timezone                 TEXT    NOT NULL DEFAULT 'UTC',
    prompt                   TEXT    NOT NULL,
    -- NULL → mint a fresh conversation each fire. When set, every
    -- run lands on the same conversation (so the agent can reference
    -- prior runs as context).
    target_conversation_id   TEXT,
    enabled                  INTEGER NOT NULL DEFAULT 1,
    last_run_at              INTEGER,
    -- One of "Success" | "Failed" | "Skipped". NULL until first run.
    last_run_status          TEXT,
    -- Computed at save + after every run. Stored in UTC unix epoch
    -- so the scheduler tick is timezone-agnostic.
    next_run_at              INTEGER,
    created_at               INTEGER NOT NULL,
    updated_at               INTEGER NOT NULL,
    CHECK (enabled IN (0, 1)),
    CHECK (last_run_status IS NULL
        OR last_run_status IN ('Success', 'Failed', 'Skipped'))
);

CREATE TABLE config_runtime_settings (
    key    TEXT PRIMARY KEY,
    value  TEXT NOT NULL
);

CREATE TABLE config_search_providers (
    kind         TEXT    PRIMARY KEY,
    enabled      INTEGER NOT NULL DEFAULT 1,
    is_default   INTEGER NOT NULL DEFAULT 0,
    config_json  TEXT    NOT NULL DEFAULT '{}',
    created_at   INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL
);

CREATE TABLE config_skills (
    id                          INTEGER NOT NULL PRIMARY KEY CHECK (id = 1),
    auto_capture_enabled        INTEGER NOT NULL DEFAULT 0
                                CHECK (auto_capture_enabled IN (0, 1)),
    auto_capture_min_tool_calls INTEGER NOT NULL DEFAULT 5
                                CHECK (auto_capture_min_tool_calls >= 1
                                       AND auto_capture_min_tool_calls <= 100),
    auto_capture_dry_run        INTEGER NOT NULL DEFAULT 0
                                CHECK (auto_capture_dry_run IN (0, 1)),
    updated_at                  INTEGER NOT NULL
, reuse_update_enabled INTEGER NOT NULL DEFAULT 0
    CHECK (reuse_update_enabled IN (0, 1)));

CREATE TABLE config_tool_access (
    tool_name        TEXT    PRIMARY KEY,
    source           TEXT    NOT NULL,        -- "builtin" | "plugin" | "mcp"
    source_id        TEXT,                    -- plugin_id, mcp server_id, or NULL for builtins
    enabled          INTEGER NOT NULL DEFAULT 1,
    allowed_classes  TEXT    NOT NULL DEFAULT '[]', -- JSON array of TrustClass strings
    description      TEXT,
    input_schema     TEXT,                    -- last-known JSON-Schema snapshot
    first_seen_at    INTEGER NOT NULL,
    last_seen_at     INTEGER NOT NULL,
    removed_at       INTEGER                  -- set when the source no longer lists it
);

CREATE TABLE config_trust_policy (
    key    TEXT PRIMARY KEY,
    value  TEXT NOT NULL
);

CREATE TABLE eval_flagged (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id TEXT    NOT NULL,
    from_seq        INTEGER NOT NULL,
    to_seq          INTEGER NOT NULL,
    label           TEXT    NOT NULL,
    tags_json       BLOB,                -- JSON array of free-form tags
    flagged_by      TEXT    NOT NULL,    -- principal_id of the operator
    flagged_at      INTEGER NOT NULL,
    notes           TEXT
);

CREATE TABLE log_entries (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts_ms           INTEGER NOT NULL,
    level           TEXT    NOT NULL,   -- TRACE | DEBUG | INFO | WARN | ERROR
    target          TEXT    NOT NULL,
    conversation_id TEXT,
    plugin_id       TEXT,
    message         TEXT    NOT NULL,
    fields_json     BLOB
);

CREATE TABLE memory_entries (
    scope        TEXT    NOT NULL,     -- e.g. principal:<id> | conversation:<id> | global
    trust_class  TEXT    NOT NULL,     -- Controller | KnownTrusted | KnownLimited | ...
    key          TEXT    NOT NULL,
    value_blob   BLOB    NOT NULL,     -- MessagePack
    ttl_expires  INTEGER,              -- NULL = permanent
    updated_at   INTEGER NOT NULL, tier         TEXT    NOT NULL DEFAULT 'warm', hits         INTEGER NOT NULL DEFAULT 0, last_used_at INTEGER, created_at   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (scope, trust_class, key)
);

CREATE TABLE memory_promotions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    scope           TEXT    NOT NULL,
    trust_class     TEXT    NOT NULL,
    key             TEXT    NOT NULL,
    from_tier       TEXT    NOT NULL,         -- snapshot of current tier at propose time
    to_tier         TEXT    NOT NULL,         -- 'hot' | 'warm' | 'cold'
    reason          TEXT    NOT NULL,         -- 'frequency' | 'recency' | 'reflection' | 'manual'
    proposed_by     TEXT    NOT NULL,         -- 'sweeper' | 'planner' | 'controller'
    proposed_at     INTEGER NOT NULL,
    decided_at      INTEGER,                  -- NULL while pending
    decision        TEXT,                     -- 'approved' | 'rejected'
    decision_note   TEXT,
    -- Loose FK; rows in memory_entries don't have a numeric id, so
    -- we keep the natural composite key here. Cascading is handled
    -- at the application layer (entry deletion is rare anyway).
    FOREIGN KEY (scope, trust_class, key)
        REFERENCES memory_entries(scope, trust_class, key)
        ON DELETE CASCADE
);

CREATE TABLE memory_reflections (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id   TEXT    NOT NULL,
    -- Anchor each reflection to the event that ended the turn it's
    -- reflecting on, so the audit trail can link "this lesson came
    -- from that model_turn". The HMAC chain in state_events makes
    -- the link tamper-evident.
    anchor_event_seq  INTEGER NOT NULL,
    context_text      TEXT    NOT NULL,        -- "what task was happening"
    reflection_text   TEXT    NOT NULL,        -- "what I observed"
    lesson_text       TEXT    NOT NULL,        -- "actionable change for next time"
    -- If the reflection produced a memory write, link the resulting
    -- promotion proposal (or NULL if it was a no-op observation).
    promotion_id      INTEGER,
    created_at        INTEGER NOT NULL,
    FOREIGN KEY (promotion_id) REFERENCES memory_promotions(id) ON DELETE SET NULL
);

CREATE TABLE principals (
    id                TEXT    PRIMARY KEY,
    identifiers_json  BLOB    NOT NULL,   -- JSON array of (transport, handle)
    trust_level_json  BLOB    NOT NULL,   -- full TrustLevel variant + fields
    resolved_by_json  BLOB    NOT NULL,   -- JSON array of PluginIds
    metadata_json     BLOB    NOT NULL,   -- display_name, tags, notes, first_seen
    first_seen        INTEGER NOT NULL,
    last_seen         INTEGER,
    controller_notes  TEXT
);

CREATE VIRTUAL TABLE skill_search USING fts5(
    description,
    body_md,
    content='state_skill_versions',
    content_rowid='id',
    tokenize='porter unicode61'
);

CREATE TABLE state_alert_silences (
    id           TEXT    PRIMARY KEY,
    matcher_json BLOB    NOT NULL,
    expires_at   INTEGER,
    created_by   TEXT    NOT NULL,
    reason       TEXT
);

CREATE TABLE state_alerts (
    id                TEXT    PRIMARY KEY,
    fingerprint       TEXT    NOT NULL,
    severity          TEXT    NOT NULL,  -- Critical | Error | Warning | Info
    source            TEXT    NOT NULL,
    title             TEXT    NOT NULL,
    detail            TEXT,
    context_json      BLOB,
    status            TEXT    NOT NULL,  -- Firing | Acked | Resolved | Snoozed
    first_seen_at     INTEGER NOT NULL,
    last_seen_at      INTEGER NOT NULL,
    occurrence_count  INTEGER NOT NULL DEFAULT 1,
    resolved_at       INTEGER,
    resolved_by       TEXT,
    ack_at            INTEGER,
    ack_by            TEXT,
    snooze_until      INTEGER,
    incident_id       TEXT,
    actions_json      BLOB
);

CREATE TABLE state_artifacts (
    id               TEXT    PRIMARY KEY,
    research_job_id  TEXT,
    kind             TEXT    NOT NULL,   -- research_pdf | image | other
    mime_type        TEXT    NOT NULL,
    path             TEXT    NOT NULL,
    sha256           TEXT    NOT NULL,
    bytes            INTEGER,
    created_at       INTEGER NOT NULL
);

CREATE TABLE state_attachments (
    id               TEXT    PRIMARY KEY,
    conversation_id  TEXT    NOT NULL,
    mime_type        TEXT    NOT NULL,
    path             TEXT    NOT NULL,
    sha256           TEXT    NOT NULL,
    received_at      INTEGER NOT NULL
);

CREATE TABLE state_blobs (
    sha256       TEXT PRIMARY KEY,                           -- 64-char hex
    bytes        BLOB NOT NULL,
    mime         TEXT NOT NULL,
    size_bytes   INTEGER NOT NULL,
    refcount     INTEGER NOT NULL DEFAULT 0,
    created_at   INTEGER NOT NULL
);

CREATE TABLE state_conversations (
    conversation_id TEXT    PRIMARY KEY,
    kind            TEXT    NOT NULL,  -- ControllerDM | GroupWithControllerPresent | ...
    last_seq        INTEGER NOT NULL DEFAULT 0,
    phase           TEXT    NOT NULL,  -- idle | thinking | awaiting_tool | ...
    controller_id   TEXT,
    trust_class     TEXT    NOT NULL,  -- Controller | KnownTrusted | ... | Blocked
    snapshot_blob   BLOB,              -- materialized view for fast resume
    snapshot_seq    INTEGER,
    lease_owner     TEXT,              -- worker id; NULL = idle
    lease_expires   INTEGER,           -- epoch seconds
    modality        TEXT    NOT NULL DEFAULT 'Text'   -- Text | Voice
, display_name TEXT, is_pinned INTEGER NOT NULL DEFAULT 0, is_ephemeral INTEGER NOT NULL DEFAULT 0, ephemeral_expires_at INTEGER, principal_group_id TEXT, last_activity_at INTEGER NOT NULL DEFAULT 0, display_name_source TEXT NOT NULL DEFAULT 'auto');

CREATE TABLE state_events (
    conversation_id TEXT    NOT NULL,
    seq             INTEGER NOT NULL,
    kind            TEXT    NOT NULL,  -- 'user_msg' | 'model_turn' | 'tool_use'
                                       -- | 'tool_result' | 'interrupt' | 'resume'
                                       -- | 'approval' | 'effect_committed' | 'wakeup'
                                       -- | 'alert_fired' | 'voice.*' | 'cold_contact_arrived'
                                       -- (non-exhaustive — event kinds are additive)
    payload         BLOB    NOT NULL,  -- MessagePack
    committed_at    INTEGER NOT NULL,
    actor           TEXT, tag    BLOB, key_id INTEGER NOT NULL DEFAULT 0,              -- PrincipalId or 'system'
    PRIMARY KEY (conversation_id, seq)
);

CREATE TABLE state_inbox (
    idempotency_key TEXT    PRIMARY KEY,
    received_at     INTEGER NOT NULL
);

CREATE TABLE state_incidents (
    id             TEXT    PRIMARY KEY,
    title          TEXT    NOT NULL,
    first_seen_at  INTEGER NOT NULL,
    resolved_at    INTEGER,
    alert_count    INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE state_oauth_clients (
    plugin_id      TEXT    NOT NULL,
    account_name   TEXT    NOT NULL,
    provider       TEXT    NOT NULL,                  -- 'google'
    client_id      TEXT    NOT NULL,
    client_secret  TEXT    NOT NULL,
    redirect_uri   TEXT    NOT NULL,
    scopes_json    TEXT    NOT NULL,                  -- JSON array of OAuth scopes (manifest-declared)
    created_at     INTEGER NOT NULL,
    updated_at     INTEGER NOT NULL,
    PRIMARY KEY (plugin_id, account_name)
);

CREATE TABLE state_oauth_pending (
    state_token   TEXT    PRIMARY KEY,                -- random 32-byte URL-safe blob
    plugin_id     TEXT    NOT NULL,
    account_name  TEXT    NOT NULL,
    redirect_to   TEXT,                                -- optional SPA URL to bounce back to after connect
    created_at    INTEGER NOT NULL,
    expires_at    INTEGER NOT NULL                    -- typically created_at + 600 (10 min)
);

CREATE TABLE state_oauth_tokens (
    plugin_id          TEXT    NOT NULL,
    account_name       TEXT    NOT NULL,
    access_token       TEXT    NOT NULL,
    refresh_token      TEXT,                          -- nullable: some providers don't issue one on re-consent
    token_expires_at   INTEGER NOT NULL,              -- unix seconds
    scopes_granted     TEXT    NOT NULL,              -- JSON array of scopes the user actually granted
    account_email      TEXT,                          -- discovered from the token (Google: id_token sub)
    created_at         INTEGER NOT NULL,
    updated_at         INTEGER NOT NULL,
    PRIMARY KEY (plugin_id, account_name),
    FOREIGN KEY (plugin_id, account_name)
        REFERENCES state_oauth_clients(plugin_id, account_name)
        ON DELETE CASCADE
);

CREATE TABLE state_outbox (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    idempotency_key TEXT    NOT NULL UNIQUE,
    conversation_id TEXT    NOT NULL,
    effect_kind     TEXT    NOT NULL,  -- transport.send | schedule.wakeup | ...
    payload         BLOB    NOT NULL,
    status          TEXT    NOT NULL,  -- pending | in_flight | delivered | failed | dead_letter
    attempts        INTEGER NOT NULL DEFAULT 0,
    next_attempt_at INTEGER,
    last_error      TEXT,
    enqueued_seq    INTEGER NOT NULL
);

CREATE TABLE state_plugins (
    plugin_id     TEXT    PRIMARY KEY,
    version       TEXT    NOT NULL,
    manifest_toml TEXT    NOT NULL,        -- verbatim plugin.toml, for audit
    stage_path    TEXT    NOT NULL,
    enabled       INTEGER NOT NULL DEFAULT 1,
    installed_at  INTEGER NOT NULL,
    updated_at    INTEGER NOT NULL
);

CREATE TABLE state_principal_group_members (
    group_id     TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    PRIMARY KEY(group_id, principal_id)
);

CREATE TABLE state_principal_groups (
    -- Internal uuid we mint. Used by the runner registry, the
    -- workspace volume name (`execlaw-runner-<group_id>`), and the
    -- foreign key from state_conversations.principal_group_id.
    group_id            TEXT PRIMARY KEY,

    -- Transport identifier: 'web' | 'whatsapp' | 'signal' | 'slack' |
    -- 'email' | ... Free-form because the channel set is plugin-driven
    -- (transport plugins land in Phase 8). The runner doesn't care
    -- about the value beyond using it as part of the lookup key.
    channel             TEXT NOT NULL,

    -- Channel's native group id when one exists (e.g. WhatsApp's
    -- group jid). NULL for transports that don't have group ids
    -- (web, ad-hoc DMs). When present, it's the authoritative
    -- identity component for `(channel, native_group_id)` lookups.
    native_group_id     TEXT,

    -- sha256 hex of the sorted principal_id set. Used as a fallback
    -- identity when `native_group_id` is NULL — two messages from
    -- the same set of principals on the same channel hash to the
    -- same group. Kept on every row (even when native_group_id is
    -- present) so the membership-driven UNIQUE constraint stays
    -- meaningful for transports that mix.
    principal_set_hash  TEXT NOT NULL,

    -- Denormalised flag for the reaper: groups containing the
    -- controller are pinned hot indefinitely (never idle-reaped,
    -- workspace never wiped). Recomputed from
    -- state_principal_group_members on every membership change.
    includes_controller INTEGER NOT NULL DEFAULT 0,

    created_at          INTEGER NOT NULL,
    last_active_at      INTEGER NOT NULL
);

CREATE TABLE state_refresh_tokens (
    token         TEXT    PRIMARY KEY,        -- the opaque refresh token string
    principal_id  TEXT    NOT NULL,           -- user_id; same value embedded in JWT `sub`
    session_id    TEXT    NOT NULL,           -- shared across rotations within one login
    issued_at     INTEGER NOT NULL,
    expires_at    INTEGER NOT NULL
);

CREATE TABLE state_research_jobs (
    -- Stable id; the runner picks rows up by it; tools return it to
    -- the model so subsequent `research_status(job_id)` calls work.
    id                  TEXT    PRIMARY KEY,
    -- Conversation that originated the job. The Card lifecycle
    -- events (CardOpened/Progressed/Closed) commit to this
    -- conversation's event log so the chat-pane renderer picks
    -- them up naturally.
    conversation_id     TEXT    NOT NULL,
    -- The original research question (operator-facing or model-
    -- generated). Bounded by the tool layer (8000 chars).
    query               TEXT    NOT NULL,
    -- Lifecycle vocabulary. Matches `core::research::JobStatus`:
    --   pending     → row inserted, runner not yet picked up
    --   planning    → runner is making the plan-phase LLM call
    --   planned     → plan landed; awaiting gather (C4)
    --   gathering   → fan-out workers running (C4)
    --   synthesizing → final report being composed (C5)
    --   complete    → terminal: report.md written + attachment_id set
    --   failed      → terminal: `error` populated
    --   cancelled   → terminal: operator cancelled cooperatively
    status              TEXT    NOT NULL DEFAULT 'pending',
    -- Caller's trust class at job creation. Capability-gated tools
    -- check the row's caller_trust before allowing reads. Stored
    -- because the runner needs to honour the original caller's
    -- scope when the operator's class might change between
    -- enqueue and read.
    caller_trust        TEXT    NOT NULL,
    -- Stable id of the operator-visible Card driving the chat-
    -- pane render. Set on `Pending → Planning` so the SPA can
    -- subscribe; `NULL` until then.
    card_id             TEXT,
    -- Plan as MessagePack-encoded `ResearchPlan`. Populated when
    -- the planner LLM call returns; stays NULL during pending /
    -- planning. C4 reads it to drive the gather workers.
    plan_json           BLOB,
    -- Per-sub-query notes (gathering output). MessagePack-encoded
    -- `Vec<ResearchNote>`. C4 writes here.
    notes_json          BLOB,
    -- Path under the workspace root (see `crate::research::workspace`)
    -- where bulky payloads live. NULL until the runner provisions
    -- the dir; absolute on disk.
    workspace_path      TEXT,
    -- Final attachment id (the synthesized report.md) once
    -- synthesize lands in C5.
    attachment_id       TEXT,
    -- Operator-safe failure message when status='failed'.
    error               TEXT,
    -- Operator-supplied per-job overrides on the global config_research
    -- defaults. JSON blob: presence of a key means the override applies.
    overrides_json      BLOB,
    -- Per-row clocks. `started_at` flips on `Pending → Planning`;
    -- `finished_at` flips on the terminal transition. `created_at`
    -- and `updated_at` are bookkeeping for the operator UI.
    created_at          INTEGER NOT NULL,
    updated_at          INTEGER NOT NULL,
    started_at          INTEGER,
    finished_at         INTEGER
);

CREATE TABLE state_routine_runs (
    id                  TEXT    PRIMARY KEY,
    routine_id          TEXT    NOT NULL,
    fired_at            INTEGER NOT NULL,    -- when the scheduler decided to fire
    started_at          INTEGER,             -- runner pickup
    finished_at         INTEGER,
    status              TEXT    NOT NULL,    -- Pending | Success | Failed | Skipped
    error               TEXT,
    conversation_id     TEXT,
    FOREIGN KEY (routine_id) REFERENCES config_routines(id) ON DELETE CASCADE,
    CHECK (status IN ('Pending', 'Success', 'Failed', 'Skipped'))
);

CREATE TABLE state_skill_invocations (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    skill_id          INTEGER NOT NULL REFERENCES state_skills(id),
    skill_version_id  INTEGER NOT NULL REFERENCES state_skill_versions(id),
    conversation_id   TEXT    NOT NULL,
    loaded_at         INTEGER NOT NULL,
    outcome           TEXT CHECK (outcome IN ('success','failure','aborted')),
    outcome_at        INTEGER,
    tool_calls_made   INTEGER,
    notes             TEXT
);

CREATE TABLE state_skill_proposals (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    proposal_kind       TEXT NOT NULL
                        CHECK (proposal_kind IN ('new_skill', 'version_fork')),
    -- For 'version_fork': the existing skill being forked.
    -- For 'new_skill': NULL (no existing skill yet).
    target_skill_id     INTEGER REFERENCES state_skills(id) ON DELETE CASCADE,
    proposed_name       TEXT NOT NULL,
    description         TEXT NOT NULL,
    body_md             TEXT NOT NULL,
    frontmatter_json    TEXT NOT NULL,
    -- Provenance: which run produced this proposal.
    source_run_id       TEXT NOT NULL,
    -- Optional model-generated summary of why the proposal was
    -- produced (e.g. "trajectory revealed a missing verification
    -- step"). Stored as plain text; renders verbatim in the UI.
    trajectory_summary  TEXT,
    tool_calls_observed INTEGER NOT NULL,
    state               TEXT NOT NULL DEFAULT 'pending'
                        CHECK (state IN ('pending', 'approved', 'rejected', 'superseded')),
    -- Set when state transitions to 'approved'.
    promoted_skill_id   INTEGER REFERENCES state_skills(id),
    promoted_version_id INTEGER REFERENCES state_skill_versions(id),
    created_at          INTEGER NOT NULL,
    reviewed_at         INTEGER,
    reviewer            TEXT,
    decision_notes      TEXT
);

CREATE TABLE state_skill_resources (
    skill_version_id INTEGER NOT NULL REFERENCES state_skill_versions(id) ON DELETE CASCADE,
    path             TEXT    NOT NULL,
    blob_sha         TEXT    NOT NULL REFERENCES state_blobs(sha256),
    PRIMARY KEY (skill_version_id, path)
);

CREATE TABLE state_skill_versions (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    skill_id            INTEGER NOT NULL REFERENCES state_skills(id) ON DELETE CASCADE,
    version             INTEGER NOT NULL,                    -- monotonic per skill, starts at 1
    description         TEXT    NOT NULL,                    -- matcher text shown in skills.list
    body_md             TEXT    NOT NULL,                    -- procedural body
    frontmatter_json    TEXT    NOT NULL,                    -- structured frontmatter
    body_sha256         TEXT    NOT NULL,                    -- content address for dedup + audit
    authored_by         TEXT    NOT NULL,                    -- 'admin:<user_id>' | 'agent:<run_id>' | 'plugin:<id>'
    authored_at         INTEGER NOT NULL,
    promotion_notes     TEXT,
    parent_version_id   INTEGER REFERENCES state_skill_versions(id),
    UNIQUE(skill_id, version)
);

CREATE TABLE state_skills (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    name                  TEXT    NOT NULL UNIQUE,
    current_version_id    INTEGER REFERENCES state_skill_versions(id),
    state                 TEXT    NOT NULL
                          CHECK (state IN ('trial','stable','archived')),
    source                TEXT    NOT NULL,                  -- 'admin' | 'plugin:<id>' | 'agent:<run_id>'
    registration_kind     TEXT    NOT NULL
                          CHECK (registration_kind IN ('authored','shipped','registered')),
    owning_plugin_id      TEXT,                              -- non-null iff registration_kind != 'authored'
    created_at            INTEGER NOT NULL,
    updated_at            INTEGER NOT NULL,
    archived_at           INTEGER
);

CREATE TABLE state_transport_bindings (
    -- Transport identifier — same string used in
    -- state_principal_groups.channel: 'signal', 'whatsapp', 'web', ...
    channel             TEXT NOT NULL,

    -- Transport's foreign id for this endpoint. For Signal: the JID
    -- (`signal:user:<uuid>` for DMs, `signal:group:<id>` for groups).
    -- For WhatsApp: the wa.me handle. For email: the canonical
    -- mailbox. Bridge plugins decide the format; the supervisor and
    -- the store just key on the literal string.
    foreign_id          TEXT NOT NULL,

    -- The execlaw principal_group_id this binding routes to.
    -- Required, NOT NULL: a binding without a target is dead weight.
    -- We don't FK because `state_principal_groups` doesn't have a
    -- foreign-key-friendly trigger story for cascade-on-delete in
    -- SQLite without WAL+foreign_keys=ON; the supervisor's delete
    -- path explicitly removes bindings when a group is destroyed
    -- (see `TransportBindingStore::forget_principal_group`).
    principal_group_id  TEXT NOT NULL,

    -- 0 = DM (foreign_id is one contact); 1 = group (foreign_id is
    -- a transport-side group id). Stored explicitly even though
    -- it's recoverable from state_principal_groups so inbound
    -- routing doesn't need the join.
    is_group            INTEGER NOT NULL DEFAULT 0,

    -- When the supervisor first observed this mapping. Useful for
    -- diagnostics ("when did we start routing this contact's
    -- messages here?") and for retention sweeps.
    created_at          INTEGER NOT NULL,

    -- Last inbound or outbound activity on this binding. The
    -- supervisor updates this on every dispatch and ingest;
    -- retention can prune bindings that haven't seen activity in N
    -- months without losing identity continuity (the principal
    -- record itself is the durable identity — bindings are the hot
    -- index).
    last_seen_at        INTEGER,

    -- (channel, foreign_id) is the natural primary key — a single
    -- foreign endpoint can only point at one principal_group at a
    -- time per transport. Re-pointing is a deliberate operator
    -- action via `upsert_binding`.
    PRIMARY KEY (channel, foreign_id)
);

CREATE TABLE state_webauthn_credentials (
    credential_id  TEXT    PRIMARY KEY,    -- base64url(authenticator-returned id)
    user_id        TEXT    NOT NULL,
    label          TEXT    NOT NULL,       -- operator-supplied nickname ("YubiKey 5C", "MacBook TouchID")
    passkey_json   TEXT    NOT NULL,       -- serde_json(webauthn_rs::Passkey)
    counter        INTEGER NOT NULL DEFAULT 0,
    created_at     INTEGER NOT NULL,
    last_used_at   INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE transport_conversations (
    plugin_id          TEXT    NOT NULL,
    transport_handle   TEXT    NOT NULL,
    principal_id       TEXT    NOT NULL,
    conversation_id    TEXT    NOT NULL,
    is_current         INTEGER NOT NULL DEFAULT 1,
    last_message_at    INTEGER NOT NULL,
    PRIMARY KEY (plugin_id, transport_handle, principal_id, conversation_id)
);

CREATE TABLE transport_cursors (
    plugin_id      TEXT    PRIMARY KEY,
    cursor_value   TEXT    NOT NULL,
    updated_at     INTEGER NOT NULL
);

CREATE TABLE users (
    user_id        TEXT    PRIMARY KEY,
    username       TEXT    NOT NULL,        -- login handle; stored lowercased (3+ chars, [a-z0-9_-])
    display_name   TEXT    NOT NULL,        -- shown in UI ("Justin Long")
    email          TEXT,
    password_hash  TEXT    NOT NULL,        -- Argon2id (§7.1)
    role           TEXT    NOT NULL,        -- "controller" | "operator" | "viewer" (Phase 7+)
    created_at     INTEGER NOT NULL,
    last_login_at  INTEGER
);

CREATE TABLE vault_secrets (
    name         TEXT    NOT NULL,   -- e.g. 'admin_password_hash', 'controller_ed25519_priv'
    plugin_id    TEXT,                -- NULL = core; otherwise plugin-scoped
    value_blob   BLOB    NOT NULL,
    created_at   INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    PRIMARY KEY (plugin_id, name)
);

-- =========================================================================
-- INDEXES
-- =========================================================================

CREATE INDEX idx_alerts_source
    ON state_alerts(source, last_seen_at);
CREATE INDEX idx_alerts_status_severity
    ON state_alerts(status, severity, last_seen_at);
CREATE INDEX idx_artifacts_research
    ON state_artifacts(research_job_id, created_at);
CREATE INDEX idx_attachments_conversation
    ON state_attachments(conversation_id, received_at);
CREATE INDEX idx_config_audit_ts
    ON config_audit(ts);
CREATE INDEX idx_config_routines_next_run_at
    ON config_routines(next_run_at)
    WHERE enabled = 1;
CREATE INDEX idx_eval_flagged_conversation
    ON eval_flagged(conversation_id, from_seq);
CREATE INDEX idx_eval_flagged_label
    ON eval_flagged(label, flagged_at);
CREATE INDEX idx_log_entries_conversation
    ON log_entries(conversation_id, ts_ms) WHERE conversation_id IS NOT NULL;
CREATE INDEX idx_log_entries_plugin
    ON log_entries(plugin_id, ts_ms) WHERE plugin_id IS NOT NULL;
CREATE INDEX idx_log_entries_ts
    ON log_entries(ts_ms);
CREATE INDEX idx_mcp_servers_enabled
    ON config_mcp_servers(enabled);
CREATE INDEX idx_memory_hits
    ON memory_entries(tier, hits, last_used_at);
CREATE INDEX idx_memory_promotions_pending
    ON memory_promotions(decided_at) WHERE decided_at IS NULL;
CREATE INDEX idx_memory_promotions_target
    ON memory_promotions(scope, trust_class, key);
CREATE INDEX idx_memory_reflections_conv
    ON memory_reflections(conversation_id, created_at);
CREATE INDEX idx_memory_reflections_recent
    ON memory_reflections(created_at);
CREATE INDEX idx_memory_tier_used
    ON memory_entries(scope, trust_class, tier, last_used_at);
CREATE INDEX idx_memory_ttl
    ON memory_entries(ttl_expires) WHERE ttl_expires IS NOT NULL;
CREATE INDEX idx_pg_members_principal
    ON state_principal_group_members(principal_id);
CREATE UNIQUE INDEX idx_principal_groups_channel_hash
    ON state_principal_groups(channel, principal_set_hash)
    WHERE native_group_id IS NULL;
CREATE UNIQUE INDEX idx_principal_groups_channel_native
    ON state_principal_groups(channel, native_group_id)
    WHERE native_group_id IS NOT NULL;
CREATE INDEX idx_refresh_tokens_expires_at
    ON state_refresh_tokens(expires_at);
CREATE INDEX idx_refresh_tokens_principal_id
    ON state_refresh_tokens(principal_id);
CREATE INDEX idx_refresh_tokens_session_id
    ON state_refresh_tokens(session_id);
CREATE INDEX idx_search_providers_default
    ON config_search_providers(is_default) WHERE is_default = 1;
CREATE INDEX idx_state_conversations_ephemeral
    ON state_conversations(is_ephemeral, ephemeral_expires_at)
    WHERE is_ephemeral = 1;
CREATE INDEX idx_state_conversations_pg
    ON state_conversations(principal_group_id);
CREATE INDEX idx_state_conversations_phase
    ON state_conversations(phase, lease_expires);
CREATE INDEX idx_state_conversations_pinned_activity
    ON state_conversations(is_pinned, last_activity_at);
CREATE INDEX idx_state_events_kind
    ON state_events(kind, committed_at);
CREATE INDEX idx_state_events_time
    ON state_events(conversation_id, committed_at);
CREATE INDEX idx_state_oauth_pending_expiry
    ON state_oauth_pending(expires_at);
CREATE INDEX idx_state_oauth_tokens_expiry
    ON state_oauth_tokens(token_expires_at);
CREATE INDEX idx_state_outbox_status
    ON state_outbox(status, next_attempt_at);
CREATE INDEX idx_state_plugins_enabled
    ON state_plugins(enabled);
CREATE INDEX idx_state_research_jobs_conv
    ON state_research_jobs(conversation_id, created_at);
CREATE INDEX idx_state_research_jobs_pending
    ON state_research_jobs(status, created_at);
CREATE INDEX idx_state_research_jobs_terminal
    ON state_research_jobs(status, finished_at);
CREATE INDEX idx_state_routine_runs_pending
    ON state_routine_runs(status)
    WHERE status = 'Pending';
CREATE INDEX idx_state_routine_runs_routine_fired
    ON state_routine_runs(routine_id, fired_at DESC);
CREATE INDEX idx_state_skill_invocations_conv
    ON state_skill_invocations(conversation_id);
CREATE INDEX idx_state_skill_invocations_skill_time
    ON state_skill_invocations(skill_id, loaded_at);
CREATE INDEX idx_state_skill_proposals_state
    ON state_skill_proposals(state, created_at);
CREATE INDEX idx_state_skill_proposals_target
    ON state_skill_proposals(target_skill_id) WHERE target_skill_id IS NOT NULL;
CREATE INDEX idx_state_skill_resources_blob
    ON state_skill_resources(blob_sha);
CREATE INDEX idx_state_skill_versions_skill
    ON state_skill_versions(skill_id);
CREATE INDEX idx_state_skills_owning_plugin
    ON state_skills(owning_plugin_id) WHERE owning_plugin_id IS NOT NULL;
CREATE INDEX idx_state_skills_state
    ON state_skills(state) WHERE state != 'archived';
CREATE INDEX idx_tool_access_source
    ON config_tool_access(source, source_id);
CREATE INDEX idx_transport_bindings_channel_last_seen
    ON state_transport_bindings(channel, last_seen_at);
CREATE INDEX idx_transport_bindings_pg
    ON state_transport_bindings(principal_group_id);
CREATE INDEX idx_transport_conv_current
    ON transport_conversations(plugin_id, transport_handle, principal_id, is_current);
CREATE INDEX idx_transport_conv_principal
    ON transport_conversations(principal_id, last_message_at);
CREATE INDEX idx_users_role ON users(role);
CREATE UNIQUE INDEX idx_users_username ON users(username);
CREATE INDEX idx_webauthn_credentials_user_id
    ON state_webauthn_credentials(user_id);
CREATE UNIQUE INDEX uq_alert_fingerprint_firing
    ON state_alerts(fingerprint) WHERE status = 'Firing';

-- =========================================================================
-- TRIGGERS
-- =========================================================================

CREATE TRIGGER trg_single_default_provider
AFTER UPDATE OF is_default ON config_search_providers
FOR EACH ROW
WHEN NEW.is_default = 1
BEGIN
    UPDATE config_search_providers
    SET is_default = 0,
        updated_at = NEW.updated_at
    WHERE kind != NEW.kind AND is_default = 1;
END;

CREATE TRIGGER trg_single_default_provider_insert
AFTER INSERT ON config_search_providers
FOR EACH ROW
WHEN NEW.is_default = 1
BEGIN
    UPDATE config_search_providers
    SET is_default = 0,
        updated_at = NEW.updated_at
    WHERE kind != NEW.kind AND is_default = 1;
END;

CREATE TRIGGER trg_state_skill_resources_ad
AFTER DELETE ON state_skill_resources
BEGIN
    UPDATE state_blobs SET refcount = refcount - 1 WHERE sha256 = OLD.blob_sha;
END;

CREATE TRIGGER trg_state_skill_resources_ai
AFTER INSERT ON state_skill_resources
BEGIN
    UPDATE state_blobs SET refcount = refcount + 1 WHERE sha256 = NEW.blob_sha;
END;

CREATE TRIGGER trg_state_skill_versions_ad
AFTER DELETE ON state_skill_versions
BEGIN
    INSERT INTO skill_search(skill_search, rowid, description, body_md)
    VALUES('delete', OLD.id, OLD.description, OLD.body_md);
END;

CREATE TRIGGER trg_state_skill_versions_ai
AFTER INSERT ON state_skill_versions
BEGIN
    INSERT INTO skill_search(rowid, description, body_md)
    VALUES (NEW.id, NEW.description, NEW.body_md);
END;

CREATE TRIGGER trg_state_skills_au
AFTER UPDATE OF current_version_id, state ON state_skills
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE state_skills SET updated_at = strftime('%s','now') * 1000
    WHERE id = NEW.id;
END;

-- =========================================================================
-- SEEDED ROWS
-- =========================================================================

INSERT OR IGNORE INTO "config_general" ("id", "start_on_boot", "bind_address", "updated_at", "setup_wizard_dismissed_at", "hf_secondary_caches_json", "history_retention_days") VALUES (1, 1, '127.0.0.1:3031', 1778435385, NULL, NULL, 30);

INSERT OR IGNORE INTO "config_personality" ("scope_kind", "scope_ref", "display_name", "role", "tone", "communication_style", "initiative", "about_agent", "about_controller", "custom_instructions", "voice_id", "override_fields_json", "version", "created_at", "updated_at") VALUES ('default', '', 'execlaw', 'Personal assistant', '', '', '', '', '', '', 'bf_emma+am_michael', '[]', 1, 1778435385, 1778435385);

INSERT OR IGNORE INTO "config_research" ("id", "max_wall_clock_minutes", "max_total_tokens", "max_subqueries", "parallel_workers", "max_urls_per_subquery", "max_pages_total", "auto_cancel_after_idle_secs", "phase_gates", "default_search_provider", "updated_at") VALUES (1, 30, 100000, 12, 3, 5, 60, 120, 'plan_only', NULL, 0);

INSERT OR IGNORE INTO "config_search_providers" ("kind", "enabled", "is_default", "config_json", "created_at", "updated_at") VALUES ('duckduckgo', 1, 1, '{}', 0, 0);

INSERT OR IGNORE INTO "config_skills" ("id", "auto_capture_enabled", "auto_capture_min_tool_calls", "auto_capture_dry_run", "updated_at", "reuse_update_enabled") VALUES (1, 0, 5, 0, 1778435385000, 0);

